### ISSUE TITLE
Can't register/link account and waifu not listed

### ISSUE THREAD

**Issue by AsylumDemon** [ace3df/AcePictureBot#78] opened 2017-04-07 23:25 UTC
I've been trying to link my account using the tweet the bot tells me to use "@AcePictureBot connect discord 'id code here" and it never seems to work as every time I try using the mywaifu command it sends me a message saying the same thing, to connect my account. I don't know if there's something wrong with my twitter settings or what (I don't hardly ever use twitter tbh). 

Another issue is looking at the waifu list I didn't find Motoko Kusanagi from Ghost in the Shell (specifically I'm looking for her Stand Alone Complex version). Is there a way to add her, or does it work through registering her? Guess it doesn't matter all that much if I can't seem to link my account anyways heh.

**Comment by ace3df** [comment] 2017-04-07 23:58
Use !apb info in discord and copy "Your ID:" or post your Twitter handle here

WaifuRegister is not limited to waifus on the waifu list. To find the person you're looking for you can use this:

https://gist.github.com/ace3df/c1865e9c1773e3762a2671badc5aeae0

**Comment by AsylumDemon** [comment] 2017-04-08 03:57
My Twitter handle is: @AsylumDemon 
ID is: 147849111704567808

I'll take a look at the register and play around with that, however I would assume it wouldn't work until I have my account linked. That being said I suppose I should've mentioned that this isn't my bot more in a server I'm in, not sure if that matters or not. Kinda feel like I'm retarded or something as this is proving to be more difficult than I thought it would be lmao.

**Comment by AsylumDemon** [comment] 2017-04-19 17:08
Was there something else I was supposed to do on my end that I missed?

**Comment by ace3df** [comment] 2017-04-19 17:40
I checked both your discord id and twitter id and you're not already in the connected accounts (this can sometimes cause such a thing e.g. moving to a new account) so I don't see what the problem is.
Step by step and tell me which one just doesn't seem to work:-
1. Say MyWaifu on Discord
2. You have been DM'd on Discord with a "Tweet this code"
3. You went onto Twitter and tweeted "@AcePicutreBot connect discord TheToken"
4. You got replied saying that it connected (reply can sometimes be hidden because of a Twitter platform thing)
5. You said WaifuRegister Girl_name and it replied
6. You said MyWaifu on Discord and got a picture of them (**if** the register was valid and worked.)

**Comment by AsylumDemon** [comment] 2017-04-19 22:56
Step 4. I can say MyWaifu on Discord and I'll get the DM every time, but tweeting that command and token I've done well over 10 times and I never get anything in response that I'm aware of. For the reply would it be hidden as like a message I'd need to accept first like with Facebook? As far as I can tell with Twitter I've never gotten a reply nor a direct message of any kind. As for the Discord accounts I only have the one, however I do have it open on my desktop and laptop usually at all times, could that be the issue?

**Comment by AsylumDemon** [comment] 2017-05-02 00:21
Do you have any idea's?

**Comment by ace3df** [comment] 2017-05-02 00:23
Please link your tweet when you tweet the connect part

**Comment by AsylumDemon** [comment] 2017-05-02 02:50
[https://twitter.com/AsylumDemon/status/850487077753962497](url)

**Comment by ace3df** [comment] 2017-05-08 18:44
I've cleaned the current token list. 
Try MyWaifu again on Discord and use the new token.

**Closed as completed by ace3df** 2017-05-08 18:44 UTC
